version: '{build}'


os: Visual Studio 2015


platform: x64


init: []


environment:
  CYGWIN_PATH: C:\cygwin64\bin\bash
  PYTHON: C:\Python36-x64\python.exe
  TESTING_RESULT: "Success"
  GITHUB_TOKEN:
    secure: gzN7IIwlku2+7LB0SO+41zfT04Iir7WgCypBx/lwniP5JbxFl4dtjjMN/jj7sQZ1
  YANDEX_DISK_TOKEN:
    secure: R//j8C73CXwMBOyzobmPYGMUz/uPo9QyQrYXpJyvPIR5EeaX7f054/z1uddYdYux
  matrix:
  - CI_JOB: "BUILD_WINDOWS_CCORE"
  - CI_JOB: "UT_WINDOWS_CCORE"
  - CI_JOB: "BUILD_CYGWIN_CCORE"
  - CI_JOB: "PYCLUSTERING_WINDOWS_X86"
  - CI_JOB: "PYCLUSTERING_WINDOWS_X64"


build_script:
  - ps: ./ci/appveyor-ci.ps1
